version: "3.7"
services:
  db:
    image: postgres
    container_name: local_pgdb
    restart: no
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - "./volumes/database/local-pgdata:/var/lib/postgresql/data"
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: no
    ports:
      - "7777:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: david.cortaberria@entelgy-ibai.com
      PGADMIN_DEFAULT_PASSWORD: frescor
    volumes:
      - "./volumes/database/pgadmin-data:/var/lib/pgadmin"
  create-gitkeep:
    image: busybox
    container_name: create-gitkeep-db
    depends_on:
      - db
    volumes:
      - "./volumes/database/local-pgdata:/var/lib/postgresql/data"
    entrypoint: sh -c "
      echo 'Esperando que Postgres termine de inicializar...';
      sleep 15;
      if [ ! -f /var/lib/postgresql/data/.gitkeep ]; then
      touch /var/lib/postgresql/data/.gitkeep;
      echo '.gitkeep creado correctamente.';
      else
      echo '.gitkeep ya existe.';
      fi
      "
    restart: "no"