version: '3.7'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.4
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - elk
  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.4
    volumes:
      - "./volumes/logstash/pipeline:/usr/share/logstash/pipeline"
      - "../../zlogs:/usr/share/logstash/logs"
    ports:
      - "5000:5000"  # Entrada TCP si quieres usarla más adelante
      - "9600:9600"  # Monitoring API
    networks:
      - elk
    depends_on:
      - elasticsearch
  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.4
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - elk
networks:
  elk: